version: '3.8'

services:
  app:
    image: fabreguesm/releasenoteservice:0.6.0
    ports:
      - target: 3000
        published: ${PUERTO}
        protocol: tcp
        mode: host
    networks:
      - traefik
    deploy:
      replicas: 1
      placement:
        constraints: ['${NODE}']
      resources:
        limits:
          memory: 1g
      update_config:
        order: stop-first
        failure_action: rollback
        monitor: 60s
      rollback_config:
        order: stop-first
    environment:
      LOCAL_ADMIN_PASSWORD: ${LOCAL_ADMIN_PASSWORD}
      SESSION_SECRET: ${SESSION_SECRET}
      PUBLIC_URL: ${PUBLIC_URL}
      INGEST_BITBUCKET_TOKEN: ${INGEST_BITBUCKET_TOKEN}
    volumes:
      - data:/data

volumes:
  data:
    name: '${SERVICE_NAME}_releasenotes_data'

networks:
  traefik:
    external: true
    name: traefik-network
